

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:"%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})- %msg%n)"}
  level:
    org.springframework.security: trace

spring:
  application:
    name: ${SPRING_APP_NAME:springsection1}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate.hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}
